[package]
name = "vs-bacnet-monitor"
description = "BACnet intrusion detection for Craton Shield (IEC 62443)"
readme = "README.md"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
vs-types.workspace = true
vs-types-ind.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
