[package]
name = "vs-iec61850-monitor"
description = "IEC 61850 MMS/GOOSE/SV intrusion detection for Craton Shield (IEC 62443)"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
vs-types.workspace = true
vs-types-ind.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
