[package]
name = "vs-autosar"
description = "Craton Shield AUTOSAR Classic/Adaptive platform integration"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[features]
stub = []

[dependencies]
vs-types = { workspace = true }
vs-types-auto = { workspace = true }
vs-hal = { workspace = true }

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
