// SPDX-License-Identifier: Apache-2.0
//! Property-based tests for security invariants.

use proptest::prelude::*;

use vs_crypto::{KeyId, NonceCounter, SoftwareCryptoProvider};
use vs_netfw::{Firewall, Verdict};
use vs_storage::{
    MonotonicCounter, RamStorageProvider, StorageProvider, MAX_KEY_LEN, MAX_VALUE_LEN,
};

// ---------------------------------------------------------------------------
// NonceCounter properties
// ---------------------------------------------------------------------------

proptest! {
    /// Every nonce generated by a NonceCounter must be unique.
    #[test]
    fn nonce_counter_all_nonces_unique(prefix in proptest::array::uniform8(0u8..)) {
        if let Ok(mut nc) = NonceCounter::new(prefix) {
            let mut seen = std::collections::HashSet::new();
            for _ in 0..500 {
                let nonce = nc.next().unwrap();
                assert!(seen.insert(nonce), "nonce collision detected");
            }
        }
    }

    /// The 8-byte prefix must be preserved in every generated nonce.
    #[test]
    fn nonce_counter_prefix_preserved(prefix in proptest::array::uniform8(0u8..)) {
        if let Ok(mut nc) = NonceCounter::new(prefix) {
            for _ in 0..100 {
                let nonce = nc.next().unwrap();
                assert_eq!(&nonce[..8], &prefix);
            }
        }
    }

    /// The counter portion must be strictly monotonically increasing.
    #[test]
    fn nonce_counter_monotonic(prefix in proptest::array::uniform8(0u8..)) {
        if let Ok(mut nc) = NonceCounter::new(prefix) {
            let mut prev_counter = 0u32;
            for _ in 0..200 {
                let nonce = nc.next().unwrap();
                let counter = u32::from_be_bytes([nonce[8], nonce[9], nonce[10], nonce[11]]);
                assert!(counter > prev_counter, "counter must increase");
                prev_counter = counter;
            }
        }
    }

    /// Persisted counter must skip ahead by the safety margin.
    #[test]
    fn nonce_counter_persisted_always_ahead(
        prefix in proptest::array::uniform8(0u8..),
        persisted in 0u32..=(u32::MAX - 2048)
    ) {
        if let Ok(nc) = NonceCounter::new_persisted(prefix, persisted) {
            assert!(nc.count() >= persisted + 1024);
        }
    }
}

// ---------------------------------------------------------------------------
// MonotonicCounter properties
// ---------------------------------------------------------------------------

proptest! {
    /// MonotonicCounter must never decrease.
    #[test]
    fn monotonic_counter_never_decreases(increments in proptest::collection::vec(1u64..100, 1..20)) {
        let mut store = RamStorageProvider::new();
        let mut ctr = MonotonicCounter::new(&mut store, b"prop").unwrap();
        let mut expected = 0u64;
        for inc in increments {
            let target = expected.saturating_add(inc);
            match ctr.advance_to(target) {
                Ok(v) => {
                    assert!(v >= expected, "counter went backwards: {v} < {expected}");
                    expected = v;
                }
                Err(_) => break,
            }
        }
    }

    /// Attempting to decrease the counter must fail.
    #[test]
    fn monotonic_counter_rejects_rollback(
        initial in 1u64..10000,
        rollback in 0u64..10000
    ) {
        let mut store = RamStorageProvider::new();
        let mut ctr = MonotonicCounter::new(&mut store, b"rb").unwrap();
        ctr.advance_to(initial).unwrap();
        if rollback < initial {
            assert!(ctr.advance_to(rollback).is_err());
            assert_eq!(ctr.value(), initial, "value must not change on rollback");
        }
    }
}

// ---------------------------------------------------------------------------
// Firewall default-deny property
// ---------------------------------------------------------------------------

proptest! {
    /// A firewall with no rules must deny all packets.
    #[test]
    fn firewall_default_deny(
        src_mac in proptest::array::uniform6(0u8..),
        dst_mac in proptest::array::uniform6(0u8..),
        ethertype in proptest::num::u16::ANY,
    ) {
        let mut fw = Firewall::new();
        let pkt = vs_eth_monitor::EthPacket {
            src_mac,
            dst_mac,
            vlan_id: None,
            ethertype,
            dst_port: None,
            payload: &[],
        };
        let verdict = fw.evaluate(&pkt, 0);
        assert_eq!(verdict, Verdict::Drop, "empty firewall must drop all packets");
    }
}

// ---------------------------------------------------------------------------
// RamStorageProvider properties
// ---------------------------------------------------------------------------

proptest! {
    /// Any key/value pair within size limits can be written and read back.
    #[test]
    fn storage_write_read_roundtrip(
        key in proptest::collection::vec(0u8.., 1..MAX_KEY_LEN),
        value in proptest::collection::vec(0u8.., 0..MAX_VALUE_LEN),
    ) {
        let mut store = RamStorageProvider::new();
        store.write(&key, &value).unwrap();
        let mut buf = [0u8; MAX_VALUE_LEN];
        let len = store.read(&key, &mut buf).unwrap();
        assert_eq!(&buf[..len], &value[..]);
    }

    /// Deleting a key must make it unreadable.
    #[test]
    fn storage_delete_removes_key(
        key in proptest::collection::vec(0u8.., 1..MAX_KEY_LEN),
        value in proptest::collection::vec(0u8.., 1..MAX_VALUE_LEN),
    ) {
        let mut store = RamStorageProvider::new();
        store.write(&key, &value).unwrap();
        store.delete(&key).unwrap();
        assert!(!store.contains(&key));
    }

    /// Overwriting must return the new value, not the old one.
    #[test]
    fn storage_overwrite_returns_new_value(
        key in proptest::collection::vec(0u8.., 1..=MAX_KEY_LEN),
        v1 in proptest::collection::vec(0u8.., 1..MAX_VALUE_LEN),
        v2 in proptest::collection::vec(0u8.., 1..MAX_VALUE_LEN),
    ) {
        let mut store = RamStorageProvider::new();
        store.write(&key, &v1).unwrap();
        store.write(&key, &v2).unwrap();
        let mut buf = [0u8; MAX_VALUE_LEN];
        let len = store.read(&key, &mut buf).unwrap();
        assert_eq!(&buf[..len], &v2[..]);
    }
}

// ---------------------------------------------------------------------------
// AES-GCM encrypt/decrypt roundtrip property
// ---------------------------------------------------------------------------

proptest! {
    /// Encrypting then decrypting must recover the original plaintext.
    #[test]
    fn aes_gcm_roundtrip(
        plaintext in proptest::collection::vec(0u8.., 0..64),
        aad in proptest::collection::vec(0u8.., 0..32),
        key_byte in 0u8..,
        nonce_seed in 1u32..,
    ) {
        use vs_crypto::CryptoProvider;
        let mut crypto = SoftwareCryptoProvider::default();
        crypto.set_key(KeyId(0), &[key_byte; 16]).unwrap();

        // Build a non-degenerate nonce from the seed (not all same byte).
        let seed_bytes = nonce_seed.to_le_bytes();
        let mut nonce = [0u8; 12];
        for (i, b) in nonce.iter_mut().enumerate() {
            *b = seed_bytes[i % 4] ^ (i as u8);
        }
        let mut ct = vec![0u8; plaintext.len()];
        let mut tag = [0u8; 16];
        crypto.aes_gcm_encrypt(KeyId(0), &nonce, &plaintext, &aad, &mut ct, &mut tag).unwrap();

        let mut pt_out = vec![0u8; plaintext.len()];
        crypto.aes_gcm_decrypt(KeyId(0), &nonce, &ct, &aad, &tag, &mut pt_out).unwrap();
        assert_eq!(pt_out, plaintext);
    }
}

// ---------------------------------------------------------------------------
// CAN Monitor properties
// ---------------------------------------------------------------------------

proptest! {
    #[test]
    fn prop_can_monitor_never_panics(
        id in 0u32..0x800,
        dlc in 0u8..=64,
        fill in 0u8..=255,
        ts in 0u64..u64::MAX / 2,
    ) {
        let mut monitor = vs_can_monitor::CanMonitor::default();
        let frame = vs_can_monitor::CanFrame {
            id,
            dlc,
            data: [fill; 64],
            is_extended: false,
            is_fd: false,
        };
        // Must not panic regardless of input
        let _ = monitor.process_frame(&frame, ts);
    }

    #[test]
    fn prop_can_monitor_extended_id_never_panics(
        id in 0u32..0x2000_0000,
        dlc in 0u8..=64,
        fill in 0u8..=255,
        ts in 0u64..u64::MAX / 2,
    ) {
        let mut monitor = vs_can_monitor::CanMonitor::default();
        let frame = vs_can_monitor::CanFrame {
            id,
            dlc,
            data: [fill; 64],
            is_extended: true,
            is_fd: false,
        };
        let _ = monitor.process_frame(&frame, ts);
    }
}

// ---------------------------------------------------------------------------
// ETH Monitor properties
// ---------------------------------------------------------------------------

proptest! {
    #[test]
    fn prop_eth_monitor_never_panics(
        src_mac in proptest::array::uniform6(0u8..),
        dst_mac in proptest::array::uniform6(0u8..),
        ethertype in proptest::num::u16::ANY,
        payload_len in 0usize..256,
        fill in 0u8..=255,
    ) {
        let mut monitor = vs_eth_monitor::EthMonitor::new(&vs_eth_monitor::EthMonitorConfig::default(), vs_eth_monitor::DEFAULT_SIPHASH_KEYS).unwrap();
        let payload = vec![fill; payload_len];
        let pkt = vs_eth_monitor::EthPacket {
            src_mac,
            dst_mac,
            vlan_id: None,
            ethertype,
            dst_port: None,
            payload: &payload,
        };
        // Must not panic regardless of input
        let _ = monitor.inspect_packet(&pkt, 1_000_000);
    }
}

// ---------------------------------------------------------------------------
// Policy Engine properties
// ---------------------------------------------------------------------------

proptest! {
    #[test]
    fn prop_policy_engine_default_deny(
        address in 0u32..1000,
        ecu_role in 0u8..=255,
    ) {
        // An empty policy engine should always deny
        let engine = vs_policy_engine::PolicyEngine::new();
        let subject = vs_policy_engine::Subject {
            address,
            authenticated: false,
            ecu_role,
            session_token: 0,
            auth_level: vs_policy_engine::AuthenticationLevel::None,
        };
        let resource = vs_policy_engine::Resource {
            bus_type: None,
            bus_id: None,
            service_id: None,
            firmware_region: None,
        };
        let action = vs_policy_engine::Action {
            action_type: vs_policy_engine::ActionType::Read,
        };
        let env = vs_policy_engine::Environment { timestamp_us: 1000 };
        let decision = engine.evaluate(&subject, &resource, &action, &env);
        prop_assert_eq!(decision.effect, vs_policy_engine::Effect::Deny);
    }
}

// ---------------------------------------------------------------------------
// Policy Engine deny-overrides combining algorithm
// ---------------------------------------------------------------------------

proptest! {
    /// When DenyOverrides is the combining algorithm and at least one rule
    /// denies, the final decision must always be Deny — regardless of how
    /// many Permit rules also match or their priorities.
    #[test]
    fn prop_policy_deny_overrides_always_denies(
        address in 0u32..1000,
        ecu_role in 0u8..=255,
        // Use even/odd split to guarantee distinct priorities.
        permit_priority in (0u8..=126).prop_map(|p| p * 2),
        deny_priority in (0u8..=126).prop_map(|p| p * 2 + 1),
    ) {
        let mut engine = vs_policy_engine::PolicyEngine::new();
        engine.set_combining_algorithm(vs_policy_engine::CombiningAlgorithm::DenyOverrides);

        // Add a Permit rule that matches everything.
        engine.add_rule(vs_policy_engine::PolicyRule {
            id: 1,
            subject: vs_policy_engine::SubjectMatcher::Any,
            resource: vs_policy_engine::ResourceMatcher::Any,
            action: vs_policy_engine::ActionMatcher::Any,
            effect: vs_policy_engine::Effect::Permit,
            priority: permit_priority,
            valid_from: 0,
            valid_until: 0,
        }).unwrap();

        // Add a Deny rule that also matches everything.
        engine.add_rule(vs_policy_engine::PolicyRule {
            id: 2,
            subject: vs_policy_engine::SubjectMatcher::Any,
            resource: vs_policy_engine::ResourceMatcher::Any,
            action: vs_policy_engine::ActionMatcher::Any,
            effect: vs_policy_engine::Effect::Deny,
            priority: deny_priority,
            valid_from: 0,
            valid_until: 0,
        }).unwrap();

        let subject = vs_policy_engine::Subject {
            address,
            authenticated: false,
            ecu_role,
            session_token: 0,
            auth_level: vs_policy_engine::AuthenticationLevel::None,
        };
        let resource = vs_policy_engine::Resource {
            bus_type: None,
            bus_id: None,
            service_id: None,
            firmware_region: None,
        };
        let action = vs_policy_engine::Action {
            action_type: vs_policy_engine::ActionType::Read,
        };
        let env = vs_policy_engine::Environment { timestamp_us: 1000 };
        let decision = engine.evaluate(&subject, &resource, &action, &env);
        prop_assert_eq!(decision.effect, vs_policy_engine::Effect::Deny,
            "DenyOverrides must always deny when any rule denies");
    }
}
