[package]
name = "vs-report-iec62443"
description = "Craton Shield IEC 62443-4-2 Security Level compliance assessor"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
vs-types = { path = "../types" }

[lints]
workspace = true
