[package]
name = "vs-mqtt-monitor"
description = "MQTT protocol intrusion detection for Craton Shield"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
readme = "README.md"

[dependencies]
vs-types = { workspace = true }
vs-types-embedded = { workspace = true }

[features]
default = []
capacity-large = ["vs-types-embedded/capacity-large"]
capacity-xl = ["vs-types-embedded/capacity-xl"]

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true
